version: '3.8'

services:
  backend:
    build: ./backend
    container_name: job_recommendation_backend
    restart: always
    environment:
      - DATABASE_URL=postgres://postgres.sxwqnadkpaheijrlqmlq:mYUiEhV0UsE0WDIx@aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require&supa=base-pooler.x
      - SECRET_KEY=super-secret-production-key-change-it-immediately-1234
      - UPLOAD_DIR=/app/uploads/resumes
    ports:
      - "8000:8000"
    volumes:
      - upload_data:/app/uploads/resumes

  frontend:
    build: ./frontend
    container_name: job_recommendation_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  upload_data:
